### ISSUE TITLE
Adding opcua and possibly comunication abstraction layer

### ISSUE THREAD

**Issue by TheFern2** [Automation-Standard/Open-Industry-Project#1]
As said on the reddit post, I will work on adding opcua. Just by looking at the code I think we need to add some interfaces so that is easy for people to add more communication protocols. I'll try to work on some comms architecture diagram before doing anything.

**Comment by tokke100** [comment]
I'm working on a siemens setup
let's collaborate

I'm using discord with @ryevdokimov at this moment. We could start an open discord server to align

**Comment by ryevdokimov** [comment]
I created a discord server: [Open Industry Project ](https://discord.gg/Jzrb9beS)

**Comment by ryevdokimov** [comment]
https://github.com/Automation-Standard/Open-Industry-Project/commit/4ab3721609a5df433ffe1f7f7c164046f8b8a72a
