### ISSUE TITLE
Add realistic stack beacon models 

### ISSUE THREAD

**Issue by ryevdokimov** [Automation-Standard/Open-Industry-Project#12]
For example: 
![image](https://user-images.githubusercontent.com/105675984/231512105-e306d35c-6010-443c-ba38-23f3b1afb0d4.png)

**Comment by MatthewReed303** [comment]
@ryevdokimov have done PR with triple stack light and color selection options. You will have to check PLC tag side of things and check it's correct.

**Comment by ryevdokimov** [comment]
Thanks, https://github.com/Automation-Standard/Open-Industry-Project/commit/f9125dacbb9e5fbde0d0825fa3f206637a28e5de
